<?php

/**
 * @file
 * Primary module hooks for Custom CSS Class to Body module.
 */

use Drupal\node\NodeInterface;

/**
 * Implements hook_preprocess_html().
 */
function uod_custom_css_class_to_body_preprocess_html(&$variables) {
  $node = \Drupal::routeMatch()->getParameter('node');
  if ($node instanceof NodeInterface) {
    $css_class = \Drupal::config('uod_custom_css_class_to_body.settings')->get('body_class');
    $page_nids = \Drupal::config('uod_custom_css_class_to_body.settings')->get('pages');
    if (in_array($node->id(), $page_nids)) {
      $variables['attributes']['class'][] = $css_class;
    }
  }
}
